server {
    listen 80;
    # .env 파일에 설정된 도메인으로 변경됩니다.
    # 실제 서버에서는 이 부분에 정확한 도메인 이름을 입력해야 합니다.
    server_name www.hundong2.xyz;

    location / {
        # 요청을 Keycloak 컨테이너로 전달합니다.
        # 'keycloak'은 docker-compose.yml에 정의된 서비스 이름입니다.
        proxy_pass http://keycloak:8080;

        # 프록시 관련 헤더 설정
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
