version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      # .env 파일에서 환경 변수를 가져옵니다.
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_DOMAIN}
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
    ports:
      - "${KEYCLOAK_PORT}:8080"
    networks:
      - keycloak-net

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    restart: always
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    networks:
      - keycloak-net
    depends_on:
      - keycloak

networks:
  keycloak-net:
    driver: bridge
